services:
  auth_service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=auth_db
      - DB_NAME=auth_db
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - .:/app
    depends_on:
      - auth_db
    networks:
      - auth_network

  auth_db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=auth_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - auth_db_data:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge

volumes:
  auth_db_data:
